export const USER_ADD = "USER_ADD";
export const USER_EDIT = "USER_EDIT";

export const FETCH_EXERCISES = "FETCH_EXERCISES";
export const ADD_EXERCISES = "ADD_EXERCISES";
export const GET_EXERCISES = "GET_EXERCISES";
export const EXERCISE_REMOVE = "EXERCISE_REMOVE";
export const EXERCISE_TOOGLE_FAVOURITE = "EXERCISE_TOOGLE_FAVOURITE";

export const FETCH_TRAININGS = "FETCH_TRAININGS";
export const GET_TARINING = "GET_TRAINING";
export const ADD_TRAINING = "ADD_TRAINING";
export const ADD_TRAININGS = "ADD_TRAININGS";
export const EDIT_TRAINING = "EDIT_TRAINING";
export const DELETE_TRAINING = "DELETE_TRAINING";
export const DELETE_TRAINING_SET = "DELETE_TRAINING_SET";
export const DELETE_TRAINING_AND_SET = "DELETE_TRAINING_AND_SET";

export const FETCH_SET = "FETCH_SET";
export const FETCHING_SET = "FETCHING_SET";
export const ADD_SET = "ADD_SET";
export const DELETE_SET = "DELETE_SET";
export const ADD_SETS= "ADD_SETS";

export const FETCH_WORKOUTS = "FETCH_WORKOUTS";
export const ADD_WORKOUT = "ADD_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const DELETE_WORKOUT_TRAINING = "DELETE_WORKOUT_TRAINING";
export const DELETE_WORKOUT_TRAINING_SET = "DELETE_WORKOUT_TRAINING_SET";
export const ADD_WORKOUT_TRAINING_SET = "ADD_WORKOUT_TRAINING_SET";

export const EDIT_DATE = "EDIT_DATE";

export const SET_CURRENT_EXERCISE = "SET_CURRENT_EXERCISE";
export const SET_CURRENT_TRAINING = "SET_CURRENT_TRAINING";
export const SET_CURRENT_WORKOUT = "SET_CURRENT_WORKOUT";
export const SET_LOADING = "SET_LOADING";

export const AUTH_PLAIN = "AUTH_PLAIN";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNIN = "USER_SIGNIN";

