export const USER_ADD = "USER_ADD";
export const USER_EDIT = "USER_EDIT";

export const ADD_EXERCISES = "ADD_EXERCISES";
export const GET_EXERCISES = "GET_EXERCISES";
export const EXERCISE_REMOVE = "EXERCISE_REMOVE";
export const EXERCISE_TOOGLE_FAVOURITE = "EXERCISE_TOOGLE_FAVOURITE";

export const TRAINING_ADD = "TRAINING_ADD";
export const TRAINING_REMOVE = "TRAINING_REMOVE";
export const TRAINING_EDIT = "TRAINING_EDIT";

export const EDIT_DATE = "EDIT_DATE";