export const USER_ADD = "USER_ADD";
export const USER_EDIT = "USER_EDIT";

export const ADD_EXERCISES = "ADD_EXERCISES";
export const GET_EXERCISES = "GET_EXERCISES";
export const EXERCISE_REMOVE = "EXERCISE_REMOVE";
export const EXERCISE_TOOGLE_FAVOURITE = "EXERCISE_TOOGLE_FAVOURITE";

export const GET_TRAININGS = "GET_TRAININGS";
export const GET_TARINING = "GET_TRAINING";
export const ADD_TRAINING = "ADD_TRAINING";
export const EDIT_TRAINING = "EDIT_TRAINING";
export const DELETE_TARINING = "DELETE_TARINING";

export const EDIT_DATE = "EDIT_DATE";

export const SET_CURRENT_EXERCISE = "SET_CURRENT_EXERCISE";
export const SET_CURRENT_TRAINING = "SET_CURRENT_TRAINING";

